timtool/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.i18n import JavaScriptCatalog

from tune.views import home, about

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^timtoolApi/', include('timtoolApi.urls')),
    url(r'^$', home, name="accueil"),
    url(r'^(?P<lang>[\w-]*)$', home, name="accueil_lang"),
    url(r'^about/$', about, name="about"),
    url(r'^tune/', include('tune.urls', namespace='tune')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^account/', include('allauth.urls')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

tune/urls.py
from django.conf.urls import url
from tune.views import (
    ListeTunes,
    ListeTunesFavoris,
    tunes_favoris_dashboard,
    generateur,
    generateur_group,
    comparateur,
    tune_lire,
    tune_lire_version,
    tune_favori_lire,
    tune_favori_add_sound,
    createABCTune,
    # DeleteTune,
    switch_favori,
    switch_status,
    delete_tune_favori,
    delete_sound
)

urlpatterns = [
    url(r'^liste/$', ListeTunes.as_view(), name="tune_liste",),
    url(r'^liste_favoris/$', ListeTunesFavoris.as_view(), name="tune_liste_favoris",),
    url(r'^liste_favoris/dashboard/$', tunes_favoris_dashboard, name="tunes_favoris_dashboard",),
    url(r'^generateur/$', generateur, name="generateur",),
    url(r'^generateur/(?P<slug>[\w-]*)$', generateur_group, name="generateur_group",),
    url(r'^comparateur/$', comparateur, name="comparateur",),
    url(r'^lire/(?P<slug>[\w-]+)$', tune_lire, name="tune_lire",),
    url(r'^lire/(?P<slug>[\w-]+)/(?P<version>[\w-]+)$', tune_lire_version, name="tune_lire_version",),
    url(r'^lire_favori/(?P<slug>[\w-]+)$', tune_favori_lire, name="tune_favori_lire",),
    url(r'^lire_favori/(?P<slug>[\w-]+)/add_sound/$', tune_favori_add_sound, name="tune_favori_add_sound",),
    url(r'^new_from_abc/$', createABCTune, name="tune_new_from_abc"),
    # url(r'^delete/(?P<slug>[\w-]+)/$', DeleteTune.as_view(), name='tune_delete'),
    url(r'^switch_favori/$', switch_favori, name='switch_favori'),
    url(r'^switch_status/$', switch_status, name='switch_status'),
    url(r'^tune_favori/delete/$', delete_tune_favori, name='delete_tune_favori'),
    url(r'^sound/delete/$', delete_sound, name='delete_sound'),
]

tune/forms.py
from django import forms
from .models import Tune
from django.utils.translation import ugettext_lazy as _


distinct_keys = Tune.objects.values('key').distinct()
AMONG = (("Tunes favoris appris", _("Only favorite learned Tunes")), ("Tunes Favoris non appris", _("Only favorite not learned Tunes")),
         ("Tous les Tunes Favoris", _("All favorite Tunes")), ("Tous les Tunes du site", _("All Tunes of Timtool")))
TYPES = ([(o.type, o.type) for o in Tune.objects.order_by("type").distinct("type")])
KEYS = [(o.key, o.key) for o in Tune.objects.order_by("key").distinct("key")]

class GenerateurForm(forms.Form):
    list_of = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'class': 'list-unstyled list-inline'}),
        choices=(("Sets", _("Sets")), ('Tunes', _('Tunes'))),
        initial="Sets",
        label=_("List of "),
        required=True
    )
    among = forms.ChoiceField(
        choices=AMONG,
        initial="Tunes Favoris appris",
        widget=forms.Select(attrs={'class': 'form-control'}),
        label=_("Among "),
        required=True
    )

    def __init__(self, *args, **kwargs):
        super(GenerateurForm, self).__init__(*args, **kwargs)
        self.fields['all_types'] = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'id': 'checkAll1', 'class': 'list-unstyled list-inline'}),
        choices=(("Yes", _("Yes")), ('No', _('No'))),
        initial="No",
        label=_("All types ?"),
        required=False,
        )

        self.fields['types'] = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'list-unstyled list-inline check1'}),
        choices=TYPES,
        # initial=[c[0] for c in Tune.objects.order_by("type").distinct("type")],
        label="Types ",
        required=True,
        error_messages={'required': _("Please select at least one type")}
        )

        self.fields['all_keys'] = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'id': 'checkAll2', 'class': 'list-unstyled list-inline'}),
        choices=(("Yes", _("Yes")), ('No', _('No'))),
        initial="No",
        label=_("All keys ?"),
        required=False,
        )
        self.fields['keys'] = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(attrs={'class': 'list-unstyled list-inline check2'}),
        choices=KEYS,
        # initial=[c[0] for c in Tune.objects.order_by("key").distinct("key")],
        label=_("Keys "),
        required=True,
        error_messages={'required': _("Please select at least a key")}
    )


class UploadABCFileForm(forms.Form):
    version = forms.CharField(
        label=_("Version"),
        max_length=50,
        required=True,
        error_messages={'required': _("Insert name of Tunebook or User")}
        )
    is_from = forms.ChoiceField(
        widget=forms.RadioSelect(attrs={'class': 'list-unstyled list-inline'}),
        choices=(("Tunebook", _("Tunebook")), ('User', _('User'))),
        initial="Tunebook",
        label=_("Tunebook or User ?"),
        required=True
    )
    file = forms.FileField(
        label=_("File "),
        required=True,
        error_messages={'required': _("Select a file")}
    )


class TextAreaABCForm(forms.Form):
    abc = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': _(".abc file here")}),
        label=_("Copy / Paste .abc file content"))


class ClypForm(forms.Form):
    name = forms.CharField(label=_("Title"), max_length=50)
    description = forms.CharField(
        label=_("Description of the sound to add"),
        widget=forms.Textarea(attrs={
            'placeholder': _('Recording of the Tune "xxx" that I have learned from "Abcdef" on "yyy" festival'),
            'rows': "2"
        }),
        required=True)
    href = forms.URLField(
        label=_("Link of the audio Clyp sound"),
        required=True,
        widget=forms.URLInput(attrs={'placeholder': 'https://clyp.it/abcdefg'}),
        error_messages={'required': _("The link of the sound is mandatory")},
    )

    def clean_href(self):
        href = self.cleaned_data['href']
        if not href.startswith("https://clyp.it/"):
            raise forms.ValidationError(_('The link must start with "https://clyp.it/"'))
        return href

tune/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse
from django.template.defaultfilters import slugify
from pathlib import Path
from django.db.models import Count
from django.db.models import Q
import random

from .models import Tune, TuneFavori, TuneFavori_group, TuneFavori_user, Audio_clyp_user_favori, Audio_clyp_group_favori, Audio_clyp, Title
from .forms import GenerateurForm, UploadABCFileForm, TextAreaABCForm, ClypForm
from user.models import User, GroupExtend
from user.forms import CompareUserForm
from tune.abc import handle_uploaded_file, handle_text_area, constructABC_from_abc, constructSVG_from_ABC, constructMIDI_from_ABC


class LoginRequiredMixin(object):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(LoginRequiredMixin, self).dispatch(request, *args, **kwargs)


def home(request, lang=None):
    tunes = Tune.objects.all()[:10]
    groups = GroupExtend.objects.all()[:10]
    users = User.objects.all()[:10]
    clyps = Audio_clyp.objects.all()[:5]
    return render(request, 'tune/accueil.html', {"tunes": tunes, "groups": groups, "users": users, "clyps": clyps})


def about(request):
    return render(request, 'tune/about.html')


class ListeTunes(ListView):
    model = Tune
    context_object_name = "tunes"
    template_name = "tune/tune_liste.html"
    paginate_by = 100

    def get_queryset(self):
        q_name = self.request.GET.get("q_name", None)
        q_type = self.request.GET.get("q_type", None)
        q_key = self.request.GET.get("q_key", None)
        q_sounds = self.request.GET.get("q_sounds", "Choose")
        tunes = Tune.objects.all()
        if q_name:
            tunes = tunes.filter(titles__name__icontains=q_name)
        if q_type:
            tunes = tunes.filter(type=q_type)
        if q_key:
            tunes = tunes.filter(key=q_key)
        if q_sounds == "HasSound":
            tunes = tunes.annotate(num_audio_user=Count("tunefavori__tunefavori_user__audio_clyp_user_favori"), num_audio_group=Count("tunefavori__tunefavori_group__audio_clyp_group_favori")).filter(Q(num_audio_user__gt=0) | Q(num_audio_group__gt=0))
        elif q_sounds == "NoSound":
            tunes = tunes.annotate(num_audio_user=Count("tunefavori__tunefavori_user__audio_clyp_user_favori"), num_audio_group=Count("tunefavori__tunefavori_group__audio_clyp_group_favori")).filter(Q(num_audio_user=0) & Q(num_audio_group=0))
        if q_name or q_type or q_key or not q_sounds == "Choose":
            messages.success(self.request, _('The following filters have been applied : "name" contains "%(name)s" | "type" = "%(type)s" | "key" = "%(key)s" | "recordings" = "%(recording)s"') % {
                'name': q_name,
                'type': q_type,
                'key': q_key,
                'recording': q_sounds
            })
        return tunes


class ListeTunesFavoris(ListView):
    model = TuneFavori_user
    context_object_name = "all_tunes_favoris"
    template_name = "tune/tune_liste_favoris.html"
    paginate_by = 200

    def get_queryset(self):
        q_name = self.request.GET.get("q_name", None)
        q_type = self.request.GET.get("q_type", None)
        q_key = self.request.GET.get("q_key", None)
        q_status = self.request.GET.get("q_status", None)
        q_sounds = self.request.GET.get("q_sounds", "Choose")
        tunes_favoris = TuneFavori_user.objects.filter(of_user=self.request.user)
        if q_name:
            tunes_favoris = tunes_favoris.filter(of_tune__name__icontains=q_name)
        if q_type:
            tunes_favoris = tunes_favoris.filter(of_tune__type=q_type)
        if q_key:
            tunes_favoris = tunes_favoris.filter(of_tune__key=q_key)
        if q_status == "Learned":
            tunes_favoris = tunes_favoris.filter(status=True)
        elif q_status == "Not learned":
            tunes_favoris = tunes_favoris.filter(status=False)
        if q_sounds == "HasSound":
            tunes_favoris = tunes_favoris.annotate(num_audio_user=Count("audio_clyp_user_favori")).filter(Q(num_audio_user__gt=0))
        elif q_sounds == "NoSound":
            tunes_favoris = tunes_favoris.annotate(num_audio_user=Count("audio_clyp_user_favori")).filter(Q(num_audio_user=0))
        if q_name or q_type or q_key or q_status == "Learned" or q_status == "Not learned" or not q_sounds == "Choose":
            messages.success(self.request, _('The following filters have been applied : "name" contains "%(name)s" | "type" = "%(type)s" | "key" = "%(key)s" | "status" = "%(status)s" | "recordings" = "%(recording)s"') % {
                'name': q_name,
                'type': q_type,
                'key': q_key,
                'status': q_status,
                'recording' : q_sounds
            })
        return tunes_favoris


@login_required
def tunes_favoris_dashboard(request):
    tunes_favoris = request.user.tunes_favoris.all()
    tunes = Tune.objects.filter(tunefavori__in=tunes_favoris)
    types = list(tunes.order_by('type').values('type').distinct())
    dashboard = {}
    dashboard["all"] = [0, 0, 0]
    for type in types:
        type = type["type"]
        all = tunes_favoris.filter(of_tune__type=type).count()
        learned = tunes_favoris.filter(of_tune__type=type, status=True).count()
        not_learned = tunes_favoris.filter(of_tune__type=type, status=False).count()
        dashboard[type] = [all, learned, not_learned]
        dashboard["all"] = [dashboard["all"][0] + all, dashboard["all"][1] + learned, dashboard["all"][2] + not_learned]

    return render(request, "tune/dashboard.html", {"dashboard": dashboard
        })


@login_required
def generateur(request):
    sets = ""
    tunes = ""
    tunes_favoris = ""
    sets_favoris = ""
    final_tunes_sets = []
    final_favoris_sets = []
    if request.method == 'POST':
        # list_of = request.POST.get("list_of", None)
        form = GenerateurForm(request.POST)
        if form.is_valid():
            list_of = form.cleaned_data["list_of"]
            among = form.cleaned_data["among"]
            types = form.cleaned_data["types"]
            keys = form.cleaned_data["keys"]
            if among == "Tunes favoris appris":
                tunes_favoris = TuneFavori_user.objects.filter(
                    status=1,
                    of_user=request.user,
                    of_tune__type__in=types,
                    of_tune__key__in=keys,
                )
                if tunes_favoris.count() == 0:
                    messages.warning(request, _(
                        'The list of "%(list_of)s" among "%(among)s" is empty. Modify your search criterias.') % {
                    'list_of': list_of,
                    'among': among
                    })
            elif among == "Tunes Favoris non appris":
                tunes_favoris = TuneFavori_user.objects.filter(
                    status=0,
                    of_user=request.user,
                    of_tune__type__in=types,
                    of_tune__key__in=keys,
                )
                if tunes_favoris.count() == 0:
                    messages.warning(request, _(
                    'The list of "%(list_of)s" among "%(among)s" is empty. Modify your search criterias.') % {
                    'list_of': list_of,
                    'among': among
                    })
            elif among == "Tous les Tunes Favoris":
                tunes_favoris = TuneFavori_user.objects.filter(
                    of_user=request.user,
                    of_tune__type__in=types,
                    of_tune__key__in=keys,
                )
                if tunes_favoris.count() == 0:
                    messages.warning(request, _(
                        'The list of "%(list_of)s" among "%(among)s" is empty. Modify your search criterias.') % {
                    'list_of': list_of,
                    'among': among
                    })
            elif among == "Tous les Tunes du site":
                tunes = Tune.objects.filter(type__in=types,
                                            key__in=keys,)
                if tunes.count() == 0:
                    messages.warning(request, _(
                        'The list of "%(list_of)s" among "%(among)s" is empty. Modify your search criterias.') % {
                    'list_of': list_of,
                    'among': among
                    })
            tunes = list(tunes)
            random.shuffle(tunes)
            tunes_favoris = list(tunes_favoris)
            random.shuffle(tunes_favoris)
            if list_of == "Sets":
                if len(tunes_favoris) > 0:
                    sets_favoris = {}
                    types_init = {}
                    for type in types:
                        types_init[type] = 0
                        sets_favoris[type] = []
                    for tune in tunes_favoris:
                        if types_init[tune.of_tune.type] == 3:
                            types_init[tune.of_tune.type] = 0
                            sets_favoris[tune.of_tune.type].insert(0, tune.of_tune.type)
                            final_favoris_sets.append(sets_favoris[tune.of_tune.type])
                            sets_favoris[tune.of_tune.type] = []
                        sets_favoris[tune.of_tune.type].append(tune)
                        types_init[tune.of_tune.type] = types_init[tune.of_tune.type] + 1
                    for key, final_set in sets_favoris.items():
                        if len(final_set) > 0:
                                final_set.insert(0, key)

tune/templates/tune/dashboard.html
{% extends "tune/layout.html" %}
{% load static %}
{% load i18n %}

{% block title %}
{% trans 'Dashboard' %}
{% endblock %}

{% block jumboTitle %}
{% trans 'Dashboard' %}
{% endblock %}

{% block jumboMessage %}
{% trans 'Dashboard of my favorite Tunes' %}
{% endblock %}

{% block timtool_body %}
<div class="row">
    <div class="col-sm-12 well">
        <h1>{% trans "Total Tunes in favorites"%} : {{dashboard.all.0}}</h1>
        <h2>{% trans "Total learned Tunes in favorites"%} : <span class="darkgreen">{{dashboard.all.1}}</span></h2>
        <h2>{% trans "Total not learned Tunes in favorites"%} : <span class="darkred">{{dashboard.all.2}}</span></h2>
        </div>
    </div>
    <div class="row">
    <div class="col-sm-12 well">
        <div class="panel panel-primary wrappedTable">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th></th>
                        <th class="widthCell">{% trans 'All' %}</th>
                        <th class="widthCell darkgreen">{% trans 'Learned' %}</th>
                        <th class="widthCell darkred">{% trans 'Not learned yet' %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for key, list in dashboard.items %}
                    <tr>
                            <th>{{key}}</th>
                            <td>{{list.0}}</td>
                            <td class="darkgreen">{{list.1}}</td>
                            <td class="darkred">{{list.2}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    </div>
{% endblock %}

tune/templates/tune/layout.html
{% extends "layout.html" %}
{% load static %}
{% load i18n %}

{% block nav %}
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- nav -->
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'accueil' %}">{% trans 'TIMTOOL v1.0' %}</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li>
        <form id="langage" class="form-inline" action="{% url 'set_language' %}" method="post">{% csrf_token %}
    <select class="form-control" name="language">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected{% endif %}>
                {{ language.name_local }} ({{ language.code }})
            </option>
        {% endfor %}
    </select>
                <button class="btn btn-success" type="submit">GO</button>
</form>          
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <div class="navbar-form btn-group">
                        <div class="form-group">
                            {% if not request.user.is_authenticated %}
                            <button class="btn btn-simple btn-sm btn-navbar">{% trans 'Anonymous' %}</button>
                            <a href="{% url 'account_login' %}" class="btn btn-success btn-sm">{% trans 'Log in' %}</a>
                            <a href="{% url 'account_signup' %}" class="btn btn-success btn-sm">{% trans 'Sign up' %}</a>
                            {% else %}
                            <button class="btn btn-simple btn-sm btn-navbar">{{request.user.username}}</button>
                            <a href="{% url 'account_logout' %}" class="btn btn-success btn-sm">{% trans 'Log out' %}</a>
                            {% endif %}
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block header %}
<div class="header">
    <div class="container-fluid">
        <button class="btn btn-success btn-sm" data-toggle="collapse" data-target="#sidebar"><i class="fa {% if request.session.toggle_menu == False %}fa-toggle-off{% else %}fa-toggle-on{% endif %}" aria-hidden="true"></i> {% if request.session.toggle_menu == False %}{% trans 'Show Menu' %}{% else %}{% trans 'Hide Menu' %}{% endif %}
        </button>
        <form id="searchTuneForm" class="form-inline pull-right hidden-xs" action="{% url 'tune:tune_liste' %}" method="GET">
            <div class='form-group'>
                <input id="inputSearchTune" type="text" class="form-control input-sm" placeholder="{% trans 'Search for a Tune' %}" name="q_name" required>
            </div>
            <button id="searchTune" type="submit" class="btn btn-success btn-sm"><i class="fa fa-search" aria-hidden="true"></i> {% trans 'Search' %}</button>
        </form>
    </div>
</div>
{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 col-sm-3 col-md-2 collapse {% if request.session.toggle_menu == False %}{% else %}in{% endif %}" id="sidebar">
            <br>
            <form id="searchTuneForm" class="form-inline visible-xs" action="{% url 'tune:tune_liste' %}" method="GET">
                <div class='form-group'>
                    <input id="inputSearchTune" type="text" class="form-control input-sm" placeholder="{% trans 'Search a Tune' %}" name="q" required>
                </div>
                <button id="searchTune" type="submit" class="btn btn-success btn-sm"><i class="fa fa-search" aria-hidden="true"></i> {% trans 'Search' %}</button>
            </form>
            <div class="list-group">
              <a href="#item-1" class="list-group-item chevron" data-toggle="collapse">
                {% trans "Links and functionalities accessible to all" as message_1 %}
                <i class="fa fa-chevron-down fa-chevron-change"></i> {% trans 'Global' %} {%include 'tip.html' with message=message_1 %}
            </a>
            <div class="list-group collapse in" id="item-1">
                <a class="list-group-item" href="{% url 'accueil' %}">
                    <i class="fa fa-home darkgreencolor" aria-hidden="true">
                    </i> {% trans 'Home' %}
                </a> 
                <a class="list-group-item" href="{% url 'tune:tune_liste' %}">
                    <i class="fa fa-music darkgreencolor" aria-hidden="true">
                    </i> Tunes
                </a>
                <a class="list-group-item" href="{% url 'user:groupe_liste' %}">
                    <i class="fa fa-users darkgreencolor" aria-hidden="true">
                    </i> {% trans 'Groups' %}
                </a>
                <a class="list-group-item" href="{% url 'user:contact' %}"><i class="fa fa-info darkgreencolor" aria-hidden="true"></i> Contact</a>
                <a class="list-group-item" href="{% url 'about' %}"><i class="fa fa-question-circle darkgreencolor" aria-hidden="true"></i> {% trans 'About' %}</a>
                {% comment %}
                <a class="list-group-item" href=""><i class="fa fa-gift" aria-hidden="true"></i> {% trans 'Make a Gift' %}</a>
                {% endcomment %}
            </div>

            <a href="#item-2" class="list-group-item chevron" data-toggle="collapse">
                {% trans "Links and features available to connected users" as message_2 %}
                <i class="fa fa-chevron-down fa-chevron-change"></i> {% trans 'Personal' %} {%include 'tip.html' with message=message_2 %}
            </a>
            <div class="list-group collapse in" id="item-2">

                {% if request.user.is_authenticated %}
                <a class="list-group-item" href="{% url 'tune:tune_liste_favoris' %}"><i class="fa fa-heart darkgreencolor" aria-hidden="true"></i> {% trans 'My Tunes' %}</a>
                <a class="list-group-item" href="{% url 'user:user_groupe_liste' %}"><i class="fa fa-handshake-o darkgreencolor" aria-hidden="true"></i> {% trans 'My Groups' %}</a>
                <a class="list-group-item" href="{% url 'tune:comparateur' %}"><i class="fa fa-random darkgreencolor" aria-hidden="true"></i> {% trans 'Comparator' %}</a>
                <a class="list-group-item" href="{% url 'tune:generateur' %}"><i class="fa fa-gear darkgreencolor" aria-hidden="true"></i> {% trans 'Generator' %}</a>
                <a class="list-group-item" href="{% url 'user:profile'%}"><i class="fa fa-user darkgreencolor" aria-hidden="true"></i> {% trans 'My Account' %}</a>
                {% else %}
                {% trans "You must be logged in to use this feature" as not_connected %}
                <a class="disabled list-group-item tooltipInfo" data-toggle="tooltip"
                title="{{not_connected}}"><i class="fa fa-heart darkgreencolor" aria-hidden="true"></i> {% trans 'My Tunes' %}</a>
                <a class="disabled list-group-item tooltipInfo" data-toggle="tooltip"
                title="{{not_connected}}"><i class="fa fa-handshake-o darkgreencolor" aria-hidden="true"></i> {% trans 'My Groups' %}</a>
                <a class="list-group-item disabled tooltipInfo" data-toggle="tooltip"
                title="{{not_connected}}"><i class="fa fa-random darkgreencolor" aria-hidden="true"></i> {% trans 'Comparator' %}</a>
                <a class="list-group-item disabled tooltipInfo" data-toggle="tooltip"
                title="{{not_connected}}" ><i class="fa fa-gear darkgreencolor" aria-hidden="true"></i> {% trans 'Generator' %}</a>
                <a class="disabled list-group-item tooltipInfo" data-toggle="tooltip"
                title="{{not_connected}}" ><i class="fa fa-user darkgreencolor" aria-hidden="true"></i> {% trans 'My Account' %}</a>
                {% endif %}
            </div>

            <a href="#item-3" class="list-group-item chevron" data-toggle="collapse">
                {% trans "Links and features available from the current page" as message_3 %}
                <i class="fa fa-chevron-down fa-chevron-change"></i> {% trans 'Current Page' %} {%include 'tip.html' with message=message_3 %}
            </a>
            <div class="list-group collapse in" id="item-3">
                {% block actions %}
                <a class="list-group-item">{% trans 'No action available on the current page' %}</a>
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="col-xs-12 {% if request.session.toggle_menu == False %}{% else %}col-sm-9 col-md-10{% endif %}" id="main">
        <div class="jumbotron">
        <div class="row">
        <div class="col-xs-9">
            <div class="row">
                <h1>{% block jumboTitle %}{% endblock %}</h1>
            </div>
            <div class="row">
            {% block jumboMessage %}{% endblock %}
            </div>
        </div>
        <div class="col-xs-3">
        {% block actions_page %}
        {% endblock %}
        </div>
        </div>
        </div>
        <div class="row main_content">
            <div class="col-xs-12">
                <div class="row">
                    {% include 'messages.html' %}
                </div>
                {% block timtool_body %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>
{% endblock %}