timtool/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.views.i18n import JavaScriptCatalog

from tune.views import home, about

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^timtoolApi/', include('timtoolApi.urls')),
    url(r'^$', home, name="accueil"),
    url(r'^(?P<lang>[\w-]*)$', home, name="accueil_lang"),
    url(r'^about/$', about, name="about"),
    url(r'^tune/', include('tune.urls', namespace='tune')),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^account/', include('allauth.urls')),
    url(r'^jsi18n/$', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

tune/urls.py
from django.conf.urls import url
from tune.views import (
    ListeTunes,
    ListeTunesFavoris,
    tunes_favoris_dashboard,
    generateur,
    generateur_group,
    comparateur,
    tune_lire,
    tune_lire_version,
    tune_favori_lire,
    tune_favori_add_sound,
    createABCTune,
    # DeleteTune,
    switch_favori,
    switch_status,
    delete_tune_favori,
    delete_sound
)

urlpatterns = [
    url(r'^liste/$', ListeTunes.as_view(), name="tune_liste",),
    url(r'^liste_favoris/$', ListeTunesFavoris.as_view(), name="tune_liste_favoris",),
    url(r'^liste_favoris/dashboard/$', tunes_favoris_dashboard, name="tunes_favoris_dashboard",),
    url(r'^generateur/$', generateur, name="generateur",),
    url(r'^generateur/(?P<slug>[\w-]*)$', generateur_group, name="generateur_group",),
    url(r'^comparateur/$', comparateur, name="comparateur",),
    url(r'^lire/(?P<slug>[\w-]+)$', tune_lire, name="tune_lire",),
    url(r'^lire/(?P<slug>[\w-]+)/(?P<version>[\w-]+)$', tune_lire_version, name="tune_lire_version",),
    url(r'^lire_favori/(?P<slug>[\w-]+)$', tune_favori_lire, name="tune_favori_lire",),
    url(r'^lire_favori/(?P<slug>[\w-]+)/add_sound/$', tune_favori_add_sound, name="tune_favori_add_sound",),
    url(r'^new_from_abc/$', createABCTune, name="tune_new_from_abc"),
    # url(r'^delete/(?P<slug>[\w-]+)/$', DeleteTune.as_view(), name='tune_delete'),
    url(r'^switch_favori/$', switch_favori, name='switch_favori'),
    url(r'^switch_status/$', switch_status, name='switch_status'),
    url(r'^tune_favori/delete/$', delete_tune_favori, name='delete_tune_favori'),
    url(r'^sound/delete/$', delete_sound, name='delete_sound'),
]

user/urls.py
from django.conf.urls import url

from user.views import (contact,
                        profile,
                        toggle_menu,
                        ListeGroups,
                        CreateGroup,
                        LireGroup,
                        updateGroup,
                        updateGroupRoles,
                        updateProfil,
                        joinGroup,
                        leaveGroup,
                        add_favoris_to_group,
                        groupe_switch_favori,
                        groupe_switch_role,
                        ListeUserGroups
                        )

urlpatterns = [
    url(r'^contact/$', contact, name="contact"),
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/update/$', updateProfil, name='profile_update'),
    url(r'^toggle_menu/$', toggle_menu, name='toggle_menu'),
    url(r'^groupe/liste/$', ListeGroups.as_view(), name="groupe_liste",),
    url(r'^groupe/new/$', CreateGroup.as_view(), name="groupe_new"),
    url(r'^groupe/lire/(?P<slug>[\w-]+)/$', LireGroup.as_view(), name="groupe_lire"),
    url(r'^groupe/update/(?P<slug>[\w-]+)/$', updateGroup, name="groupe_update"),
    url(r'^groupe/update_roles/(?P<slug>[\w-]+)/$', updateGroupRoles, name="groupe_update_roles"),
    url(r'^groupe/join/$', joinGroup, name="groupe_join"),
    url(r'^groupe/leave/$', leaveGroup, name="groupe_leave"),
    url(r'^groupe/add_favoris/(?P<slug>[\w-]+)/$', add_favoris_to_group, name="groupe_add_favoris"),
    url(r'^groupe/switch_favori/$', groupe_switch_favori, name='groupe_switch_favori'),
    url(r'^groupe/switch_role/$', groupe_switch_role, name='groupe_switch_role'),
    url(r'^groupe/mygroups/$', ListeUserGroups.as_view(), name='user_groupe_liste'),
]

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, DetailView, FormView
from django.core.urlresolvers import reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.template.defaultfilters import slugify
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext as _
from django.conf import settings

from .forms import ContactForm, GroupForm, UserForm
from tune.models import Tune, TuneFavori_group
from .models import GroupExtend, UserGroupRole
from tune.views import LoginRequiredMixin


User = get_user_model()


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        sujet = form.cleaned_data['sujet']
        message = form.cleaned_data['message']
        envoyeur = form.cleaned_data['envoyeur']
        renvoi = form.cleaned_data['renvoi']
        mail_to = [settings.DEFAULT_FROM_EMAIL]
        message = message + " --- Sent by : " + envoyeur
        if renvoi:
            mail_to.append(envoyeur)

        send_mail(sujet,
                  message,
                  envoyeur,
                  mail_to,
                  fail_silently=True,
                  )
        messages.success(request, _('Your email has successfully been sent !'))
        return redirect("accueil")

    return render(request, 'user/contact.html', locals())


@login_required
def profile(request):
    tunes_added = Tune.objects.filter(added_by=request.user)
    groupes_added = GroupExtend.objects.filter(created_by=request.user)
    return render(request, 'user/profile.html', {'tunes_added': tunes_added, 'groupes_added': groupes_added})


def toggle_menu(request):
    boolean = request.POST.get('boolean', None)
    if boolean == "true":
        request.session['toggle_menu'] = True
        return HttpResponse("true")
    else:
        request.session['toggle_menu'] = False
        return HttpResponse("false")


class ListeGroups(ListView):
    model = GroupExtend
    context_object_name = "groups"
    template_name = "user/groupe_liste.html"
    paginate_by = 200

    def get_queryset(self):
        q_name = self.request.GET.get("q_name", None)
        groups = GroupExtend.objects.all()
        if q_name:
            groups = groups.filter(name__icontains=q_name)
        if q_name:
            messages.success(self.request, _('The following filter has been applied : "name" contains "%(name)s"') % {
                'name': q_name,
                })
        return groups


class CreateGroup(SuccessMessageMixin, LoginRequiredMixin, FormView):
    template_name = 'user/groupe_new.html'
    form_class = GroupForm

    def form_valid(self, form):
        group = ""
        try:
            group = GroupExtend.objects.get(name=form.cleaned_data.get("name"))
        except GroupExtend.DoesNotExist:
            group = GroupExtend.objects.create_groupextend(name=form.cleaned_data.get("name"), description=form.cleaned_data.get("description"), created_by=self.request.user)
            new_user_group_role = UserGroupRole(of_group=group, of_user=self.request.user, role="admin")
            new_user_group_role.save()
            group.user_roles.add(new_user_group_role)
            self.request.user.groupe_roles.add(new_user_group_role)
            messages.success(self.request, _('The group "%(groupname)s" has been created.') % {
                'groupname': group.name
                             })
            return redirect("user:groupe_liste")
        messages.warning(
            self.request, _('The group "%(groupname)s" already exists !') % {
                'groupname': group.name
            })
        return render(self.request, "user/groupe_new.html", {"form": form})

    def get_success_url(self):
        return reverse('user:groupe_liste')


class LireGroup(DetailView):
    context_object_name = "group"
    model = GroupExtend
    template_name = "user/groupe_lire.html"

    def get_object(self):
        group = super(LireGroup, self).get_object()
        group.nb_vues = group.nb_vues + 1
        group.save()
        return group


@login_required
def updateGroup(request, slug):
    group = GroupExtend.objects.get(slug=slug)
    if not request.user.is_admin_of_this_group(request, group):
        return redirect("user:groupe_liste")
    form = GroupForm(request.POST or None, initial={'name': group.name, "description": group.description})
    if form.is_valid():
        if slugify(form.cleaned_data["name"]) != slug:
            try:
                group2 = GroupExtend.objects.get(name=form.cleaned_data.get("name"))
                messages.warning(request, _('The group "%(groupname)s" already exists !') % {'groupname': form.cleaned_data.get("name")})
                return render(request, 'user/groupe_update.html', {"form": form, "group": group})
            except GroupExtend.DoesNotExist:
                group.name = form.cleaned_data["name"]
                group.slug = slugify(group.name)
        group.description = form.cleaned_data["description"]
        group.save()
        messages.success(request, _('The group "%(groupname)s" has been updated') % {'groupname': group.name})
        return redirect('user:groupe_lire', slug=group.slug)
    return render(request, 'user/groupe_update.html', {"form": form, "group": group})


@login_required
def updateGroupRoles(request, slug):
    group = GroupExtend.objects.get(slug=slug)
    if not request.user.is_admin_of_this_group(request, group):
        return redirect("user:groupe_liste")
    return render(request, 'user/groupe_update_roles.html', {"group": group})


@login_required
def updateProfil(request):
    user = User.objects.get(username=request.user.username)
    form = UserForm(request.POST or None, initial={'username': user.username, "email": user.email})
    if form.is_valid():
        if form.cleaned_data["username"] != user.username:
            try:
                user = User.objects.get(username=form.cleaned_data.get("username"))
                messages.warning(request, _('The user "%(username)s" already exists') % {'username': user.username})
                return render(request, 'user/profil_update.html', {"form": form, "user": user})
            except User.DoesNotExist:
                user.username = form.cleaned_data["username"]
        # user.first_name = form.cleaned_data["first_name"]
        # user.last_name = form.cleaned_data["last_name"]
        user.email = form.cleaned_data["email"]
        user.save()
        messages.success(request, _('Your profile has been updated'))
        return redirect('user:profile')
    return render(request, 'user/profil_update.html', {"form": form})


@login_required
def joinGroup(request):
    group = request.POST.get('groupe_id', None)
    group_to_add = GroupExtend.objects.get(id=group)
    new_user_group_role = UserGroupRole(of_group=group_to_add, of_user=request.user, role="member")
    new_user_group_role.save()
    request.user.groupe_roles.add(new_user_group_role)
    group_to_add.user_roles.add(new_user_group_role)
    messages.success(request, _('You have joined the group'))
    return redirect('user:groupe_lire', slug=group_to_add.slug)


@login_required
def leaveGroup(request):
    group = request.POST.get('groupe_id', None)
    group_to_leave = GroupExtend.objects.get(id=group)
    if request.user.groupe_roles.get(of_group=group_to_leave, of_user=request.user).role == "admin":
        messages.error(request, _('You can\'t leave this group because you are the last administrator'))
    else:
        user_group_role = UserGroupRole.objects.get(of_group=group_to_leave, of_user=request.user)
        user_group_role.delete()
        messages.success(request, _('You left this group'))
    return redirect('user:groupe_lire', slug=group_to_leave.slug)


@login_required
def add_favoris_to_group(request, slug):
    group = GroupExtend.objects.get(slug=slug)
    if not request.user.is_admin_of_this_group(request, group):
        return redirect("user:groupe_liste")
    return render(request, 'user/groupe_add_favoris.html', {"group": group})


@login_required
def groupe_switch_favori(request):
    tune_slug = request.POST.get('tune_slug', None)
    groupe_id = request.POST.get('groupe_id', None)
    if tune_slug and groupe_id:
        try:
            tune_favori = TuneFavori_group.objects.get(of_group=groupe_id, of_tune__slug=tune_slug)
            if not request.user.is_admin_of_this_group(request, tune_favori.of_group):
                return HttpResponse("unchanged")
        except TuneFavori_group.DoesNotExist:
            tune_favori = None

        if tune_favori:
            tune_favori.delete()
            return HttpResponse("deleted")
        else:
            tune = Tune.objects.get(slug=tune_slug)
            group = GroupExtend.objects.get(id=groupe_id)
            create_tune_favori = TuneFavori_group(of_group=group, of_tune=tune)
            create_tune_favori.save()
            group.tunes_favoris.add(create_tune_favori)
            json = {"status": "added",
                    "tune_name": create_tune_favori.of_tune.name,
                    "tune_type": create_tune_favori.of_tune.type,
                    "tune_key": create_tune_favori.of_tune.key,
                    "tune_favori_id": create_tune_favori.id
                    }
            return JsonResponse(json)
    return HttpResponse("unchanged")


@login_required
def groupe_switch_role(request):
    user_role_id = request.POST.get('user_role_id')
    user_role_value = request.POST.get('user_role_value')
    myself = request.POST.get('myself')
    if user_role_id and (user_role_value == "Admin" or user_role_value == "Member"):
        user_role = UserGroupRole.objects.get(id=user_role_id)

user/templates/user/contact.html
{% extends "user/layout.html" %}
{% load static %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %}
{% trans 'Contact' %}
{% endblock %}

{% block jumboTitle %}
{% trans 'Contact' %}
{% endblock %}

{% block jumboMessage %}
{% trans 'Contact me using the following form !' %}
{% endblock %}

{% block timtool_body %}
{% if envoi %}{% trans 'Your message has been sent !' %}{% endif %}

<div class="col-xs-12 col-sm-11 col-md-10 col-lg-9">
<form action="{% url 'user:contact' %}" method="post">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <input type="submit" class="btn btn-success" value="{% trans 'Send' %}" />
</form>
</div>
{% endblock %}

user/templates/user/groupe_lire.html
{% extends "tune/layout.html" %}
{% load static %}
{% load user_filters %}
{% load tune_filters %}
{% load i18n %}

{% block title %}
{{ group.name }}
{% endblock %}

{% block jumboTitle %}
{{ group.name|truncatechars:30 }}
{% endblock %}

{% block jumboMessage %}
{% blocktrans with nb_vues=group.nb_vues %}Seen {{ nb_vues }} times{% endblocktrans %}
{% endblock %}

{% block timtool_body %}
        <div class="row well">
            <div class="col-xs-12">
<ul  class="nav nav-pills">
    <li class="active">
        <a  href="#1a" data-toggle="tab">{% trans 'Description' %}</a>
    </li>
    <li><a href="#2a" data-toggle="tab">{% trans 'Favorite Tunes' %}</a></li>
    <li><a href="#3a" data-toggle="tab">{% trans 'Members' %}</a></li>
</ul>
</div>
</div>
        <div class="row well">
            <div class="col-xs-12">
<div class="tab-content clearfix">
  <div class="tab-pane active" id="1a">
      <h1>{% trans 'Description' %}</h1>
      <p>{{group.description}}</p>
  </div>
  <div class="tab-pane" id="2a">
    {% trans "This tune has sound linked to it !" as music %}
      <h1>{% trans 'Favorite Tunes of the group' %}</h1>
      <div class="panel panel-primary wrappedTable">
        <table class="table table-striped table-hover">
            {% if group.tunes_favoris.all|length == 0 %}
            <thead><tr><th>{% trans 'You have not added any Tunes in favorites.' %}</th></tr></thead>
            {% else %}
            <thead>
                <tr>
                    <th class="widthCell">{% trans 'Name' %}</th>
                    <th class="">{% trans 'Type' %}</th>
                    <th class="">{% trans 'Key' %}</th>
                    <th>{% trans 'Status' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for tune_favori in group.tunes_favoris.all %}
                <tr data-id="{{tune_favori.of_tune.name}}">
                    <td class="tuneName"><a
                        href="{% url 'tune:tune_favori_lire' slug=tune_favori.slug %}"
                        class="btn-link tooltipInfo" data-toggle="tooltip"
                        title="Go to : {{ tune_favori.of_tune.name }}"><span>{{ tune_favori.of_tune.name }}</span>
                        <i class="fa fa-chevron-circle-right" aria-hidden="true"></i></a>
                            {% if tune_favori|tune_favori_has_sound %}
                            {% include 'music.html' with message=music %}
                            {% endif %}
                    </td>
                        <td class="">{{ tune_favori.of_tune.type }}</td>
                        <td class="">{{ tune_favori.of_tune.key }}</td>
                        <td>
                                    {% if tune_favori.status == False %}
                                    {% if user|role_of_this_group:group == "admin" %}
                                    <button data-id="{{tune_favori.slug}}" class="btn btn-simple status tooltipInfo" data-toggle="tooltip" title="{% trans 'Tune to learn' %}" type="button">
                                    <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                                    </button>
                                    {% else %}
                                    <button class="btn btn-simple tooltipInfo" data-toggle="tooltip" title="{% trans 'Only administrators can use this functionnality' %}" type="button">
                                    <i class="fa fa-thumbs-down" aria-hidden="true"></i>
                                    </button>
                                    {% endif %}
                                    {% else %}
                                    {% if user|role_of_this_group:group == "admin" %}
                                    <button data-id="{{tune_favori.slug}}" class="btn btn-simple status tooltipInfo" data-toggle="tooltip" title="{% trans 'Tune learnt' %}" type="button">
                                    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                    </button>
                                    {% else %}
                                    <button class="btn btn-simple tooltipInfo" data-toggle="tooltip" title="{% trans 'Only administrators can use this functionnality' %}" type="button">
                                    <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                                    </button>
                                    {% endif %}
                                    {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
                {% endif %}
            </table>
        </div>
    </div>
    <div class="tab-pane" id="3a">
      <h1>{% trans 'Group members' %}</h1>
      <div class="panel panel-primary wrappedTable">
        <table class="table table-striped table-hover">
            {% if group.user_roles.all|length == 0 %}
            <thead><tr><th>{% trans 'This group has not any member yet.' %}</th></tr></thead>
            {% else %}
            <thead>
                <tr>
                    <th class="widthCell">{% trans 'Username' %}</th>
                    <th>{% trans 'Role' %}</th>
                </tr>
            </thead>
            <tbody>
                {% for user_role in group.user_roles.all %}
                <tr>
                    <td class="">{{ user_role.of_user.username }}</td>
                    <td class="">{{ user_role.role}}</td>
                </tr>
                {% endfor %}
                <tr class="joined" hidden>
                    <td class=""></td>
                    <td class=""></td>
                </tr>
            </tbody>
            {% endif %}
        </table>
        </div>
</div>
</div> 
</div>
</div>
{% include 'disqus.html' with PAGE_IDENTIFIER="Group : "|add:group.slug %}
{% endblock %}

{% block actions %}
{% trans "You must be logged in to use this feature" as not_connected %}
{% if request.user.is_authenticated %}
{% if user|role_of_this_group:group == "admin" %}
<a class="list-group-item" href="{% url 'user:groupe_update' slug=group.slug%}">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Update this group' %}
</a>
{% else %}
<a class="list-group-item disabled tooltipInfo" data-toggle="tooltip"
title="{% trans 'Only administrators can use this functionnality' %}">
<i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Update this group' %}
</a>
{% endif %}
{% else %}
<a class="list-group-item disabled tooltipInfo" data-toggle="tooltip"
title="{{not_connected}}">
<i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Update this group' %}
</a>
{% endif %}

{% if user|role_of_this_group:group == "admin" %}
<a class="list-group-item" href="{% url 'user:groupe_add_favoris' slug=group.slug%}">
    <i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Add favorites' %}
</a>
{% else %}
<a class="list-group-item disabled tooltipInfo" data-toggle="tooltip"
title="{% trans 'Only administrators can use this functionnality' %}">
<i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Add favorites' %}
</a>
{% endif %}


{% if request.user.is_authenticated %}
{% if request.user|is_member:group.slug %}
<form action="{% url 'user:groupe_leave' %}" method="post">
    {% csrf_token %}
    <input name="groupe_id" value="{{group.id}}" hidden>
    <button type="submit" class="list-group-item">
        <i class="fa fa-sign-out" aria-hidden="true"></i> {% trans 'Leave this group' %}
    </button>
</form>
{% else %}
<form action="{% url 'user:groupe_join' %}" method="post">
    {% csrf_token %}
    <input name="groupe_id" value="{{group.id}}" hidden>
    <button type="submit" class="list-group-item">
        <i class="fa fa-sign-in" aria-hidden="true"></i> {% trans 'Join this group' %}
    </button>
</form>
{% endif %}
{% else %}
<button class="list-group-item tooltipInfo disabled" data-toggle="tooltip"
title="{{not_connected}}">
<i class="fa fa-sign-in" aria-hidden="true"></i> {% trans 'Join this group' %}e</button>
{% endif %}
{% endblock %}

{% block actions_page %}

<div class="row">
    {% if request.user.is_authenticated %}
    <a class="btn btn-success" href="{% url 'tune:generateur_group' slug=group.slug%}">
        <i class="fa fa-heartbeat" aria-hidden="true"></i> {% trans 'Generate Sets/Tunes' %}
    </a>
    {% else %}
    <button class="btn btn-success disabled tooltipInfo" data-toggle="tooltip"
    title="{% trans 'Only administrators can use this functionnality' %}">
    <i class="fa fa-heartbeat" aria-hidden="true"></i> {% trans 'Generate Sets/Tunes' %}
</button>
{% endif %}
</div>

<div class="row">
    {% if request.user.is_authenticated %}
    {% if user|role_of_this_group:group == "admin" %}
    <a class="btn btn-success" href="{% url 'user:groupe_update' slug=group.slug%}">
        <i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Update this group' %}
    </a>
    {% else %}
    <button class="btn btn-success disabled tooltipInfo" data-toggle="tooltip"
    title="{% trans 'Only administrators can use this functionnality' %}">
    <i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Update this group' %}
</button>
{% endif %}
{% else %}
<button class="btn btn-success disabled tooltipInfo" data-toggle="tooltip"
title="{{not_connected}}">
<i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Update this group' %}
</button>
{% endif %}
</div>

<div class="row">
    {% if user|role_of_this_group:group == "admin" %}
    <a class="btn btn-success" href="{% url 'user:groupe_add_favoris' slug=group.slug%}">
        <i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Add favorites' %}
    </a>
    {% else %}
    <button class="btn btn-success disabled tooltipInfo" data-toggle="tooltip"
    title="{% trans 'Only administrators can use this functionnality' %}">
    <i class="fa fa-plus" aria-hidden="true"></i> {% trans 'Add favorites' %}
</button>
{% endif %}
</div>

<div class="row">
    {% if user|role_of_this_group:group == "admin" %}
    <a class="btn btn-success" href="{% url 'user:groupe_update_roles' slug=group.slug%}">
        <i class="fa fa-user-circle-o" aria-hidden="true"></i> {% trans 'Update members roles' %}
    </a>
    {% else %}
    <button class="btn btn-success disabled tooltipInfo" data-toggle="tooltip"
    title="{% trans 'Only administrators can use this functionnality' %}">
        <i class="fa fa-user-circle-o" aria-hidden="true"></i> {% trans 'Update members roles' %}
    </button>
{% endif %}
</div>
<div class="row">
    {% if request.user.is_authenticated %}
    {% if request.user|is_member:group.slug %}
    <form action="{% url 'user:groupe_leave' %}" method="post">
        {% csrf_token %}
        <input name="groupe_id" value="{{group.id}}" hidden>
        <button type="submit" class="btn btn-success tooltipInfo" data-toggle="tooltip" title="{% trans 'You are member of this group' %}">
            <i class="fa fa-sign-out" aria-hidden="true"></i> {% trans 'Leave this group' %}
        </button>
    </form>
    {% else %}
    <form action="{% url 'user:groupe_join' %}" method="post">
        {% csrf_token %}
        <input name="groupe_id" value="{{group.id}}" hidden>
        <button type="submit" class="btn btn-success tooltipInfo" data-toggle="tooltip" title="{% trans 'You are not member of this group' %}">
            <i class="fa fa-sign-in" aria-hidden="true"></i> {% trans 'Join this group' %}
        </button>
    </form>
    {% endif %}
    {% else %}
    <button class="btn btn-success tooltipInfo" data-toggle="tooltip"
    title="{{not_connected}}" disabled>
    <i class="fa fa-sign-in" aria-hidden="true"></i> {% trans 'Join this group' %}</button>
    {% endif %}
</div>
{% endblock %}

user/templates/user/groupe_new.html
{% extends "tune/layout.html" %}
{% load static %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %}
{% trans 'Group creation' %}
{% endblock %}

{% block jumboTitle %}
{% trans 'Group creation' %}
{% endblock %}

{% block jumboMessage %}
{% trans 'Create a group filling the following form' %}
{% endblock %}

{% block timtool_body %}
<div class="col-xs-12 col-sm-11 col-md-10 col-lg-9">
<form action="" method="post">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <input type="submit" class="btn btn-success" value="{% trans 'Create' %}" />
</form>
</div>
{% endblock timtool_body %}

user/templates/user/groupe_update.html
{% extends "tune/layout.html" %}
{% load static %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %}
{% trans 'Modify' %} "{{group.name}}" 
{% endblock %}

{% block jumboTitle %}
{% trans 'Modify' %} "{{group.name}}" 
{% endblock %}

{% block jumboMessage %}
{% trans 'Modify the group' %} "{{group.name}}" {% trans 'filling the following form' %}
{% endblock %}

{% block timtool_body %}
<div class="col-xs-12 col-sm-11 col-md-10 col-lg-9">
<form action="" method="post">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <input type="submit" class="btn btn-success" value="{% trans 'Send' %}" />
</form>
</div>
{% endblock timtool_body %}

{% block actions %}
        <a class="list-group-item" href="{% url 'user:groupe_lire' slug=group.slug %}">
            <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> {% trans 'Back to the description' %}
        </a>
{% endblock %}

    {% block actions_page %}
        <a class="btn btn-success" href="{% url 'user:groupe_lire' slug=group.slug %}">
            <i class="fa fa-arrow-circle-left" aria-hidden="true"></i> {% trans 'Back to the description' %}
        </a>
    {% endblock %}

user/templates/user/layout.html
{% extends "tune/layout.html" %}

user/templates/user/profil_update.html
{% extends "tune/layout.html" %}
{% load static %}
{% load bootstrap_tags %}
{% load i18n %}

{% block title %}
{% trans 'Modify' %} "{{user.username}}" 
{% endblock %}

{% block jumboTitle %}
{% trans 'Modify' %} "{{user.username}}" 
{% endblock %}

{% block jumboMessage %}
{% trans 'Update user' %} "{{user.username}}" {% trans 'filling the following form' %}
{% endblock %}

{% block timtool_body %}
<div class="col-xs-12 col-sm-11 col-md-10 col-lg-9">
<form action="" method="post">
    {% csrf_token %}
    {{ form|as_bootstrap }}
    <input type="submit" class="btn btn-success" value="{% trans 'Update' %}" />
</form>
</div>
{% endblock timtool_body %}